
#SUBSCRIBED https://raw.githubusercontent.com/sbunkov/stash-configuration/main/config-ru-inside-iphone.yaml
mode: rule
ipv6: false
log-level: error
allow-lan: false
unified-delay: true
dns:
  enable: true
  ipv6: false
  default-nameserver: [1.1.1.1, 8.8.8.8]
  nameserver: ['https://dns10.quad9.net/dns-query', 'https://dns.aa.net.uk/dns-query']
sniffer:
  enable: true
  sniff:
    HTTP:
      ports: [80, 8080-8880]
      override-destination: true
    TLS:
      ports: [443, 8443]
    QUIC:
      ports: [443, 8443]
  skip-domain:
    - 'Mijia Cloud'
    - +.lan
    - +.local
proxy-providers:
  sub:
    type: http
    path: ./profiles/proxies/sub.yaml
    url: 'https://domain.com/sub' #Ссылка на подписку base64
    interval: 86400
    health-check:
      enable: true
      url: 'http://www.gstatic.com/generate_204'
      interval: 300
    benchmark-url: http://www.gstatic.com/generate_204
proxy-groups:
  - name: "AUTO"
    type: url-test
    use:
      - sub
    url: 'http://www.gstatic.com/generate_204'
    interval: 300
    icon: 'https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Proxy.png'
  - name: YOUTUBE
    type: select
    use:
      - sub
    proxies:
      - AUTO
      - DIRECT
    icon: 'https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/YouTube.png'
  - name: DISCORD
    type: select
    use:
      - sub
    proxies:
      - AUTO
      - DIRECT
    icon: 'https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Discord.png'
  - name: AI
    type: select
    use:
      - sub
    proxies:
      - AUTO
      - DIRECT
    icon: 'https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/ChatGPT.png'
  - name: ANIME
    type: select
    use:
      - sub
    proxies:
      - AUTO
      - DIRECT
    icon: 'https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Rainbow_1.png'
  - name: INSTAGRAM
    type: select
    use:
      - sub
    proxies:
      - AUTO
      - DIRECT
    icon: 'https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Instagram.png'
  - name: KINOPUB
    type: select
    use:
      - sub
    proxies:
      - AUTO
      - DIRECT
    icon: 'https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Paramount.png'
  - name: TWITTER
    type: select
    use:
      - sub
    proxies:
      - AUTO
      - DIRECT
    icon: 'https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/X.png'
  - name: TIKTOK
    type: select
    use:
      - sub
    proxies:
      - AUTO
      - DIRECT
    icon: 'https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/TikTok.png'
  - name: SPOTIFY
    type: select
    use:
      - sub
    proxies:
      - AUTO
      - DIRECT
    icon: 'https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Spotify.png'
  - name: STEAM-STORE
    type: select
    use:
      - sub
    proxies:
      - AUTO
      - DIRECT
    icon: 'https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Steam.png'
  - name: LOVE
    type: select
    use:
      - sub
    proxies:
      - AUTO
      - DIRECT
    icon: 'https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Pornhub.png'
  - name: CHECK
    type: select
    use:
      - sub
    proxies:
      - AUTO
      - DIRECT
    icon: 'https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Global.png'
  - name: OTHER
    type: select
    use:
      - sub
    proxies:
      - AUTO
      - DIRECT
    icon: 'https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Proxy.png'
rule-providers:
  youtube:
    behavior: classical
    type: http
    url: "https://raw.githubusercontent.com/mishkajackson/Rules/refs/heads/main/Clash/Domains/Youtube.yaml"
    interval: 86400
    path: ./ruleset/youtube.yaml
  discord:
    behavior: classical
    type: http
    url: "https://raw.githubusercontent.com/mishkajackson/Rules/refs/heads/main/Clash/Domains/Discord.yaml"
    interval: 86400
    path: ./ruleset/discord.yaml
  discord-voice:
    behavior: classical
    type: http
    url: "https://raw.githubusercontent.com/mishkajackson/Rules/refs/heads/main/Clash/IPs/Discord.yaml"
    interval: 86400
    path: ./ruleset/discord_voice.yaml
  ai:
    behavior: classical
    type: http
    url: "https://raw.githubusercontent.com/mishkajackson/Rules/refs/heads/main/Clash/Domains/AI.yaml"
    interval: 86400
    path: ./ruleset/ai.yaml
  anime:
    behavior: classical
    type: http
    url: "https://raw.githubusercontent.com/mishkajackson/Rules/refs/heads/main/Clash/Domains/Anime.yaml"
    interval: 86400
    path: ./ruleset/anime.yaml
  instagram:
    behavior: classical
    type: http
    url: "https://raw.githubusercontent.com/mishkajackson/Rules/refs/heads/main/Clash/Domains/Instagram.yaml"
    interval: 86400
    path: ./ruleset/instagram.yaml
  kinopub:
    behavior: classical
    type: http
    url: "https://raw.githubusercontent.com/mishkajackson/Rules/refs/heads/main/Clash/Domains/KinoPub.yaml"
    interval: 86400
    path: ./ruleset/kinopub.yaml
  twitter:
    behavior: classical
    type: http
    url: "https://raw.githubusercontent.com/mishkajackson/Rules/refs/heads/main/Clash/Domains/Twitter.yaml"
    interval: 86400
    path: ./ruleset/twitter.yaml
  tiktok:
    behavior: classical
    type: http
    url: "https://raw.githubusercontent.com/mishkajackson/Rules/refs/heads/main/Clash/Domains/TikTok.yaml"
    interval: 86400
    path: ./ruleset/tiktok.yaml
  spotify:
    behavior: classical
    type: http
    url: "https://raw.githubusercontent.com/mishkajackson/Rules/refs/heads/main/Clash/Domains/Spotify.yaml"
    interval: 86400
    path: ./ruleset/spotify.yaml
  steam-store:
    behavior: classical
    type: http
    url: "https://raw.githubusercontent.com/mishkajackson/Rules/refs/heads/main/Clash/Domains/Steam_Store.yaml"
    interval: 86400
    path: ./ruleset/steam-store.yaml
  love:
    behavior: classical
    type: http
    url: "https://raw.githubusercontent.com/mishkajackson/Rules/refs/heads/main/Clash/Domains/Love_full.yaml"
    interval: 86400
    path: ./ruleset/love.yaml
  check:
    behavior: classical
    type: http
    url: "https://raw.githubusercontent.com/mishkajackson/Rules/refs/heads/main/Clash/Domains/Check.yaml"
    interval: 86400
    path: ./ruleset/check.yaml
  other:
    behavior: classical
    type: http
    url: "https://raw.githubusercontent.com/mishkajackson/Rules/refs/heads/main/Clash/Domains/Other.yaml"
    interval: 86400
    path: ./ruleset/other.yaml
rules:
  - RULE-SET,youtube,YOUTUBE
  - RULE-SET,discord,DISCORD
  - RULE-SET,discord-voice,DISCORD
  - RULE-SET,ai,AI
  - RULE-SET,anime,ANIME
  - RULE-SET,instagram,INSTAGRAM
  - RULE-SET,kinopub,KINOPUB
  - RULE-SET,twitter,TWITTER
  - RULE-SET,tiktok,TIKTOK
  - RULE-SET,spotify,SPOTIFY
  - RULE-SET,steam-store,STEAM-STORE
  - RULE-SET,love,LOVE
  - RULE-SET,check,CHECK
  - RULE-SET,other,OTHER
  - MATCH,DIRECT
subscribe-url: https://whereland.online/eUAiQHHLfneWo0tMAnYYPi0x9X4pZQ/user
proxies:
  - # Finland
    alterId: 0
    cipher: ""
    client-fingerprint: chrome
    flow: xtls-rprx-vision
    name: HostVDS
    port: 443
    reality-opts:
      public-key: ZRsaDil0DRMPGP6Inx5ti7UKuN5ZCOPzyZbTmapjXHI
      short-id: 22dff0
    server: www.whereland.online
    servername: whereland.online
    sni: whereland.online
    tls: true
    type: vless
    uuid: d6b625a6-fe08-42a8-ada5-22b50c4f767f
