#SUBSCRIBED https://raw.githubusercontent.com/sbunkov/stash-configuration/main/config-ru-inside-iphone.yaml
mode: rule
ipv6: false
log-level: error
allow-lan: false
unified-delay: true
dns:
  enable: true
  ipv6: false
  default-nameserver: [1.1.1.1, 8.8.8.8]
  nameserver: ['https://dns10.quad9.net/dns-query', 'https://dns.aa.net.uk/dns-query']
sniffer:
  enable: true
  sniff:
    HTTP:
      ports: [80, 8080-8880]
      override-destination: true
    TLS:
      ports: [443, 8443]
    QUIC:
      ports: [443, 8443]
  skip-domain:
    - 'Mijia Cloud'
    - +.lan
    - +.local
proxy-providers:
  sub:
    type: http
    path: ./profiles/proxies/proxies.yaml
    url: 'https://raw.githubusercontent.com/sbunkov/stash-configuration/main/proxies.yaml'
    interval: 86400
    health-check:
      enable: true
      url: 'http://www.gstatic.com/generate_204'
      interval: 300
    benchmark-url: http://www.gstatic.com/generate_204
proxy-groups:
  - name: "AUTO"
    type: url-test
    use:
      - sub
    url: 'http://www.gstatic.com/generate_204'
    interval: 300
    icon: 'https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Proxy.png'
  - name: MANUAL
    type: select
    proxies:
      - HostVDS Finland
      - EOFVPN Russia
      - EOFVPN Germany
      - Freedomline
    icon: 'https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Proxy.png'
  - name: Russia Inside
    type: select
    use:
      - sub
    proxies:
      - AUTO
      - MANUAL
      - DIRECT
    icon: 'https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Russia.png'
  - name: YouTube
    type: select
    use:
      - sub
    proxies:
      - AUTO
      - MANUAL
      - DIRECT
    icon: 'https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/YouTube.png'
  - name: Discord
    type: select
    use:
      - sub
    proxies:
      - AUTO
      - MANUAL
      - DIRECT
    icon: 'https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Discord.png'
  - name: AI
    type: select
    use:
      - sub
    proxies:
      - AUTO
      - MANUAL
      - DIRECT
    icon: 'https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/ChatGPT.png'
  - name: Anime
    type: select
    use:
      - sub
    proxies:
      - AUTO
      - MANUAL
      - DIRECT
    icon: 'https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Rainbow_1.png'
  - name: Instagram
    type: select
    use:
      - sub
    proxies:
      - AUTO
      - MANUAL
      - DIRECT
    icon: 'https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Instagram.png'
  - name: Kinopub
    type: select
    use:
      - sub
    proxies:
      - AUTO
      - MANUAL
      - DIRECT
    icon: 'https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Paramount.png'
  - name: Twitter
    type: select
    use:
      - sub
    proxies:
      - AUTO
      - MANUAL
      - DIRECT
    icon: 'https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/X.png'
  - name: TikTok
    type: select
    use:
      - sub
    proxies:
      - AUTO
      - MANUAL
      - DIRECT
    icon: 'https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/TikTok.png'
  - name: Spotify
    type: select
    use:
      - sub
    proxies:
      - AUTO
      - MANUAL
      - DIRECT
    icon: 'https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Spotify.png'
  - name: Steam
    type: select
    use:
      - sub
    proxies:
      - AUTO
      - MANUAL
      - DIRECT
    icon: 'https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Steam.png'
  - name: xxx
    type: select
    use:
      - sub
    proxies:
      - AUTO
      - MANUAL
      - DIRECT
    icon: 'https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Pornhub.png'
  - name: Check
    type: select
    use:
      - sub
    proxies:
      - AUTO
      - MANUAL
      - DIRECT
    icon: 'https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Global.png'
  - name: Other
    type: select
    use:
      - sub
    proxies:
      - AUTO
      - MANUAL
      - DIRECT
    icon: 'https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Proxy.png'
rule-providers:
  russia-inside:
    behavior: classical
    type: http
    url: "https://raw.githubusercontent.com/sbunkov/stash-configuration/main/rules/ru-inside.txt"
    interval: 86400
    path: ./ruleset/russia-inside.txt
    format: text
  youtube:
    behavior: classical
    type: http
    url: "https://raw.githubusercontent.com/mishkajackson/Rules/refs/heads/main/Clash/Domains/Youtube.yaml"
    interval: 86400
    path: ./ruleset/youtube.yaml
  discord:
    behavior: classical
    type: http
    url: "https://raw.githubusercontent.com/mishkajackson/Rules/refs/heads/main/Clash/Domains/Discord.yaml"
    interval: 86400
    path: ./ruleset/discord.yaml
  discord-voice:
    behavior: classical
    type: http
    url: "https://raw.githubusercontent.com/mishkajackson/Rules/refs/heads/main/Clash/IPs/Discord.yaml"
    interval: 86400
    path: ./ruleset/discord_voice.yaml
  ai:
    behavior: classical
    type: http
    url: "https://raw.githubusercontent.com/mishkajackson/Rules/refs/heads/main/Clash/Domains/AI.yaml"
    interval: 86400
    path: ./ruleset/ai.yaml
  anime:
    behavior: classical
    type: http
    url: "https://raw.githubusercontent.com/mishkajackson/Rules/refs/heads/main/Clash/Domains/Anime.yaml"
    interval: 86400
    path: ./ruleset/anime.yaml
  instagram:
    behavior: classical
    type: http
    url: "https://raw.githubusercontent.com/mishkajackson/Rules/refs/heads/main/Clash/Domains/Instagram.yaml"
    interval: 86400
    path: ./ruleset/instagram.yaml
  kinopub:
    behavior: classical
    type: http
    url: "https://raw.githubusercontent.com/mishkajackson/Rules/refs/heads/main/Clash/Domains/KinoPub.yaml"
    interval: 86400
    path: ./ruleset/kinopub.yaml
  twitter:
    behavior: classical
    type: http
    url: "https://raw.githubusercontent.com/mishkajackson/Rules/refs/heads/main/Clash/Domains/Twitter.yaml"
    interval: 86400
    path: ./ruleset/twitter.yaml
  tiktok:
    behavior: classical
    type: http
    url: "https://raw.githubusercontent.com/mishkajackson/Rules/refs/heads/main/Clash/Domains/TikTok.yaml"
    interval: 86400
    path: ./ruleset/tiktok.yaml
  spotify:
    behavior: classical
    type: http
    url: "https://raw.githubusercontent.com/mishkajackson/Rules/refs/heads/main/Clash/Domains/Spotify.yaml"
    interval: 86400
    path: ./ruleset/spotify.yaml
  steam:
    behavior: classical
    type: http
    url: "https://raw.githubusercontent.com/mishkajackson/Rules/refs/heads/main/Clash/Domains/Steam_Store.yaml"
    interval: 86400
    path: ./ruleset/steam-store.yaml
  xxx:
    behavior: classical
    type: http
    url: "https://raw.githubusercontent.com/mishkajackson/Rules/refs/heads/main/Clash/Domains/Love_full.yaml"
    interval: 86400
    path: ./ruleset/love.yaml
  check:
    behavior: classical
    type: http
    url: "https://raw.githubusercontent.com/mishkajackson/Rules/refs/heads/main/Clash/Domains/Check.yaml"
    interval: 86400
    path: ./ruleset/check.yaml
  other:
    behavior: classical
    type: http
    url: "https://raw.githubusercontent.com/mishkajackson/Rules/refs/heads/main/Clash/Domains/Other.yaml"
    interval: 86400
    path: ./ruleset/other.yaml
rules:
  - RULE-SET,russia-inside,AUTO
  - RULE-SET,youtube,DIRECT
  - RULE-SET,discord,AUTO
  - RULE-SET,discord-voice,AUTO
  - RULE-SET,ai,AUTO
  - RULE-SET,anime,AUTO
  - RULE-SET,instagram,AUTO
  - RULE-SET,kinopub,AUTO
  - RULE-SET,twitter,AUTO
  - RULE-SET,tiktok,AUTO
  - RULE-SET,spotify,AUTO
  - RULE-SET,steam,AUTO
  - RULE-SET,xxx,AUTO
  - RULE-SET,check,AUTO
  - RULE-SET,other,AUTO
  - MATCH,DIRECT
proxies:
  - name: HostVDS Finland
    type: vless
    server: www.whereland.online
    port: 443
    uuid: d6b625a6-fe08-42a8-ada5-22b50c4f767f
    alterId: 0
    cipher: ""
    flow: xtls-rprx-vision
    tls: true
    servername: whereland.online
    sni: whereland.online
    client-fingerprint: chrome
    reality-opts:
      public-key: ZRsaDil0DRMPGP6Inx5ti7UKuN5ZCOPzyZbTmapjXHI
      short-id: 22dff0
      
  - name: "EOFVPN Russia"
    type: vmess
    server: 89.23.113.148
    port: 8081
    uuid: "ccdb0ab5-b8aa-4bf2-af09-afe0d20aa462"
    alterID: 0
    cipher: auto
    network: http
    ws-opts:
      path: /
      headers:
        Host: coursera.org
    udp: true
    
  - name: "EOFVPN Germany"
    type: vmess
    server: 147.45.178.107
    port: 8081
    uuid: "ccdb0ab5-b8aa-4bf2-af09-afe0d20aa462"
    alterID: 0
    cipher: auto
    network: http
    ws-opts:
      path: /
      headers:
        Host: cdn.jsdelivr.net
    udp: true

  - name: "Freedomline"
    type: wireguard
    server: 45.144.52.124
    port: 51745
    publicKey: "LbQ44BvQnWpvDkttnu8PAXRlTt5H5uY/smUic9CQSHI="
    privateKey: "WFWNv0zEoUfG8ewjf+i/B1QgXOwYzId2TNsk+dTEfF4="
    addresses:
      - "10.9.8.29"
    dns:
      - 8.8.8.8
    udp: true
